### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by cni30** [MomoyamaSawa/OS_PageStorage#1]
# My code encountered the following unresolved errors while running:
```python
Traceback (most recent call last):
File "start. py", line 9, in<module>
From core. instruction import*
File "C: \ Users \ echo \ Desktop \ OS-PageStorage main \ OS-PageStorage main \ core \ instruction. py", line 2, in<module>
From core. memory import*
File "C: \ Users \ echo \ Desktop \ OS-PageStorage main \ OS-PageStorage main \ core \ memory. py", line 13, in<module>
Class MemAlgorithm (ABC):
File "C: \ Users \ 13627 \ Desktop \ OS-PageStorage main \ OS-PageStorage main \ core \ memory. py", line 15, in MemAlgorithm
Def replace (self, pageID: int, list: list) ->list [int, list, int]:
TypeError: 'type' object is not subscribable
```
I have tried changing the `def getPage (ins: int, pageLen: int) ->list [int, int] `in tool.py to `def getPage (ins: int, pageLen: int) ->List [int, int]:`, but this did not work. Could you please help me take a look? Thank you

**Comment by cni30** [comment]
I have resolved it because my Python version is `3.8`, and in Python versions 3.8 and below, it is not supported to specify the container type's contained type during type annotation, for example:
```python
x: List [int, int]=[1,2]
```
But this feature is supported in versions 3.9 and above. I changed the version to `3.9` to solve this problem. Thank you again
